package initdiscovery

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

const header = `# Generated by ` + "`forge init`" + ` — deterministic repository-policy discovery.
# No LLM was involved. Review any "TODO" markers below before running forge;
# forge does not guess at a value it cannot confirm from the repository.
`

// Render marshals result.Config to YAML and annotates it with comments
// derived from result.Notes: a per-line "# TODO: ..." comment for fields
// Detect could not resolve, and header comments for informational notes
// (e.g. agent-instruction presence) that have no corresponding Config
// field. The output always parses back into an equal Config — comments
// never change the data, only annotate it — so it round-trips through
// config.Load.
func Render(result Result) ([]byte, error) {
	body, err := yaml.Marshal(result.Config)
	if err != nil {
		return nil, fmt.Errorf("initdiscovery: marshal config: %w", err)
	}

	var lineNotes []Note
	var gatesNote *Note
	var buf bytes.Buffer
	buf.WriteString(header)

	for _, n := range result.Notes {
		switch {
		case n.Field == "agent_instructions":
			buf.WriteString("#\n# " + n.Message + "\n")
		case n.Field == "quality.gates":
			note := n
			gatesNote = &note
		default:
			lineNotes = append(lineNotes, n)
		}
	}
	buf.WriteString("\n")

	lines := strings.Split(strings.TrimRight(string(body), "\n"), "\n")
	for _, line := range lines {
		buf.WriteString(line)
		if note := matchLineNote(line, lineNotes); note != nil {
			buf.WriteString("  # TODO: " + note.Message)
		}
		if gatesNote != nil && isGatesLine(line) {
			buf.WriteString("  # TODO: " + gatesNote.Message)
		}
		buf.WriteString("\n")
	}

	return buf.Bytes(), nil
}

var leafKeyRE = regexp.MustCompile(`^\s*([A-Za-z_][A-Za-z0-9_]*):`)

// matchLineNote finds the Note (if any) whose Field's final dotted segment
// names the YAML key this line defines. Field leaf names used by Detect
// (base, type) are unique across Config's schema, so a leaf-key match is
// unambiguous without tracking full YAML nesting.
func matchLineNote(line string, notes []Note) *Note {
	m := leafKeyRE.FindStringSubmatch(line)
	if m == nil {
		return nil
	}
	key := m[1]
	for i := range notes {
		segments := strings.Split(notes[i].Field, ".")
		if segments[len(segments)-1] == key {
			return &notes[i]
		}
	}
	return nil
}

func isGatesLine(line string) bool {
	return strings.TrimSpace(strings.SplitN(line, ":", 2)[0]) == "gates"
}
