package initdiscovery

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

const header = `# Generated by ` + "`forge init`" + ` — deterministic repository-policy discovery.
# No LLM was involved. Review any "TODO" markers below before running forge;
# forge does not guess at a value it cannot confirm from the repository.
`

// Render marshals result.Config to YAML and annotates it with comments
// derived from result.Notes: a "# TODO: ..." line comment on the exact
// field a Note describes, and header comments for informational notes
// (e.g. agent-instruction presence) that have no corresponding Config
// field.
//
// Notes are attached by walking result.Config's encoded yaml.Node tree
// along the Note's full dotted Field path (e.g. "git", "base") rather than
// matching by leaf key name — Config has several duplicate leaf names
// (retry.review vs workflow.review, ci vs retry.ci) that a leaf-only match
// would silently misattribute a comment to. The comment is set on the
// *key* node for the final path segment, not the value node: a block
// sequence/mapping value (e.g. quality.gates, a list) has no inline slot
// on the "key:" line for a LineComment, and yaml.v3 silently reattaches
// such a comment to the following sibling's line instead — setting it on
// the key node itself renders correctly regardless of the value's kind or
// style. Comments are metadata on the Node tree, never data, so the
// output always round-trips through config.Load to an equal Config.
func Render(result Result) ([]byte, error) {
	var root yaml.Node
	if err := root.Encode(result.Config); err != nil {
		return nil, fmt.Errorf("initdiscovery: encode config: %w", err)
	}

	var buf bytes.Buffer
	buf.WriteString(header)

	for _, n := range result.Notes {
		if n.Field == "agent_instructions" || n.Field == "lsp_no_server" {
			buf.WriteString("#\n# " + n.Message + "\n")
			continue
		}
		key, ok := walkPathKey(&root, strings.Split(n.Field, "."))
		if !ok {
			// Defensive: a Note whose Field doesn't resolve to a node in
			// the encoded Config (e.g. a typo introduced by a future
			// change) still surfaces, just as a header comment rather
			// than silently vanishing.
			buf.WriteString("#\n# " + n.Field + ": " + n.Message + "\n")
			continue
		}
		key.LineComment = "TODO: " + n.Message
	}
	buf.WriteString("\n")

	body, err := yaml.Marshal(&root)
	if err != nil {
		return nil, fmt.Errorf("initdiscovery: marshal config: %w", err)
	}
	buf.Write(body)

	return buf.Bytes(), nil
}

// walkPathKey descends root (a *yaml.Node produced by Node.Encode, or a
// DocumentNode wrapping one) through a sequence of mapping keys and
// returns the *key* node for the final path segment — the node whose
// LineComment renders on that field's own "key:" line — or false if any
// segment along the path isn't found.
func walkPathKey(root *yaml.Node, path []string) (*yaml.Node, bool) {
	node := root
	if node.Kind == yaml.DocumentNode {
		if len(node.Content) == 0 {
			return nil, false
		}
		node = node.Content[0]
	}

	for i, seg := range path {
		if node.Kind != yaml.MappingNode {
			return nil, false
		}
		key, value, found := lookupKey(node, seg)
		if !found {
			return nil, false
		}
		if i == len(path)-1 {
			return key, true
		}
		node = value
	}
	return nil, false
}

// lookupKey finds key seg within mapping node m and returns both its key
// and value nodes. Mapping nodes store content as an alternating [key0,
// value0, key1, value1, ...] slice.
func lookupKey(m *yaml.Node, seg string) (key, value *yaml.Node, ok bool) {
	for i := 0; i+1 < len(m.Content); i += 2 {
		if m.Content[i].Value == seg {
			return m.Content[i], m.Content[i+1], true
		}
	}
	return nil, nil, false
}
